# Generated by Django 3.2.9 on 2022-03-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcquestion',
            name='memory_limit',
            field=models.IntegerField(default=100000000, null=True),
        ),
        migrations.AddField(
            model_name='rcquestion',
            name='time_limt',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
